// Code generated by github.com/mackee/go-sqlla/v2/cmd/sqlla - DO NOT EDIT.
package asyncdataloader

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"database/sql"

	"github.com/mackee/go-sqlla/v2"
)

type itemsSQL struct {
	where sqlla.Where
}

func NewItemsSQL() itemsSQL {
	q := itemsSQL{}
	return q
}

var itemsAllColumns = []string{
	"`id`", "`name`",
}

type itemsSelectSQL struct {
	itemsSQL
	Columns     []string
	order       string
	limit       *uint64
	offset      *uint64
	tableAlias  string
	joinClauses []string

	additionalWhereClause     string
	additionalWhereClauseArgs []interface{}

	groupByColumns []string

	isForUpdate bool
}

func (q itemsSQL) Select() itemsSelectSQL {
	return itemsSelectSQL{
		q,
		itemsAllColumns,
		"",
		nil,
		nil,
		"",
		nil,
		"",
		nil,
		nil,
		false,
	}
}

func (q itemsSelectSQL) Or(qs ...itemsSelectSQL) itemsSelectSQL {
	ws := make([]sqlla.Where, 0, len(qs))
	for _, q := range qs {
		ws = append(ws, q.where)
	}
	q.where = append(q.where, sqlla.ExprOr(ws))
	return q
}

func (q itemsSelectSQL) Limit(l uint64) itemsSelectSQL {
	q.limit = &l
	return q
}

func (q itemsSelectSQL) Offset(o uint64) itemsSelectSQL {
	q.offset = &o
	return q
}

func (q itemsSelectSQL) ForUpdate() itemsSelectSQL {
	q.isForUpdate = true
	return q
}

func (q itemsSelectSQL) TableAlias(alias string) itemsSelectSQL {
	q.tableAlias = "`" + alias + "`"
	return q
}

func (q itemsSelectSQL) SetColumns(columns ...string) itemsSelectSQL {
	q.Columns = make([]string, 0, len(columns))
	for _, column := range columns {
		if strings.ContainsAny(column, "(.`") {
			q.Columns = append(q.Columns, column)
		} else {
			q.Columns = append(q.Columns, "`"+column+"`")
		}
	}
	return q
}

func (q itemsSelectSQL) JoinClause(clause string) itemsSelectSQL {
	q.joinClauses = append(q.joinClauses, clause)
	return q
}

func (q itemsSelectSQL) AdditionalWhereClause(clause string, args ...interface{}) itemsSelectSQL {
	q.additionalWhereClause = clause
	q.additionalWhereClauseArgs = args
	return q
}

func (q itemsSelectSQL) appendColumnPrefix(column string) string {
	if q.tableAlias == "" || strings.ContainsAny(column, "(.") {
		return column
	}
	return q.tableAlias + "." + column
}

func (q itemsSelectSQL) GroupBy(columns ...string) itemsSelectSQL {
	q.groupByColumns = make([]string, 0, len(columns))
	for _, column := range columns {
		if strings.ContainsAny(column, "(.`") {
			q.groupByColumns = append(q.groupByColumns, column)
		} else {
			q.groupByColumns = append(q.groupByColumns, "`"+column+"`")
		}
	}
	return q
}

func (q itemsSelectSQL) ID(v ItemID, exprs ...sqlla.Operator) itemsSelectSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: q.appendColumnPrefix("`id`")}
	q.where = append(q.where, where)
	return q
}

func (q itemsSelectSQL) IDIn(vs ...ItemID) itemsSelectSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: q.appendColumnPrefix("`id`")}
	q.where = append(q.where, where)
	return q
}

func (q itemsSelectSQL) PkColumn(pk int64, exprs ...sqlla.Operator) itemsSelectSQL {
	v := ItemID(pk)
	return q.ID(v, exprs...)
}

func (q itemsSelectSQL) OrderByID(order sqlla.Order) itemsSelectSQL {
	q.order = " ORDER BY " + q.appendColumnPrefix("`id`")
	if order == sqlla.Asc {
		q.order += " ASC"
	} else {
		q.order += " DESC"
	}

	return q
}

func (q itemsSelectSQL) Name(v string, exprs ...sqlla.Operator) itemsSelectSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprString{Value: v, Op: op, Column: q.appendColumnPrefix("`name`")}
	q.where = append(q.where, where)
	return q
}

func (q itemsSelectSQL) NameIn(vs ...string) itemsSelectSQL {
	where := sqlla.ExprMultiString{Values: vs, Op: sqlla.MakeInOperator(len(vs)), Column: q.appendColumnPrefix("`name`")}
	q.where = append(q.where, where)
	return q
}

func (q itemsSelectSQL) OrderByName(order sqlla.Order) itemsSelectSQL {
	q.order = " ORDER BY " + q.appendColumnPrefix("`name`")
	if order == sqlla.Asc {
		q.order += " ASC"
	} else {
		q.order += " DESC"
	}

	return q
}

func (q itemsSelectSQL) ToSql() (string, []interface{}, error) {
	columns := strings.Join(q.Columns, ", ")
	wheres, vs, err := q.where.ToSql()
	if err != nil {
		return "", nil, err
	}

	tableName := "`items`"
	if q.tableAlias != "" {
		tableName = tableName + " AS " + q.tableAlias
		pcs := make([]string, 0, len(q.Columns))
		for _, column := range q.Columns {
			pcs = append(pcs, q.appendColumnPrefix(column))
		}
		columns = strings.Join(pcs, ", ")
	}
	query := "SELECT " + columns + " FROM " + tableName
	if len(q.joinClauses) > 0 {
		jc := strings.Join(q.joinClauses, " ")
		query += " " + jc
	}
	if wheres != "" {
		query += " WHERE" + wheres
	}
	if q.additionalWhereClause != "" {
		query += " " + q.additionalWhereClause
		if len(q.additionalWhereClauseArgs) > 0 {
			vs = append(vs, q.additionalWhereClauseArgs...)
		}
	}
	if len(q.groupByColumns) > 0 {
		query += " GROUP BY "
		gbcs := make([]string, 0, len(q.groupByColumns))
		for _, column := range q.groupByColumns {
			gbcs = append(gbcs, q.appendColumnPrefix(column))
		}
		query += strings.Join(gbcs, ", ")
	}
	query += q.order
	if q.limit != nil {
		query += " LIMIT " + strconv.FormatUint(*q.limit, 10)
	}
	if q.offset != nil {
		query += " OFFSET " + strconv.FormatUint(*q.offset, 10)
	}

	if q.isForUpdate {
		query += " FOR UPDATE"
	}

	return query + ";", vs, nil
}

func (s Items) Select() itemsSelectSQL {
	return NewItemsSQL().Select().ID(s.ID)
}
func (q itemsSelectSQL) Single(db sqlla.DB) (Items, error) {
	q.Columns = itemsAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return Items{}, err
	}

	row := db.QueryRow(query, args...)
	return q.Scan(row)
}

func (q itemsSelectSQL) SingleContext(ctx context.Context, db sqlla.DB) (Items, error) {
	q.Columns = itemsAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return Items{}, err
	}

	row := db.QueryRowContext(ctx, query, args...)
	return q.Scan(row)
}

func (q itemsSelectSQL) All(db sqlla.DB) ([]Items, error) {
	rs := make([]Items, 0, 10)
	q.Columns = itemsAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}

	rows, err := db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		r, err := q.Scan(rows)
		if err != nil {
			return nil, err
		}
		rs = append(rs, r)
	}
	return rs, nil
}

func (q itemsSelectSQL) AllContext(ctx context.Context, db sqlla.DB) ([]Items, error) {
	rs := make([]Items, 0, 10)
	q.Columns = itemsAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		r, err := q.Scan(rows)
		if err != nil {
			return nil, err
		}
		rs = append(rs, r)
	}
	return rs, nil
}

func (q itemsSelectSQL) Scan(s sqlla.Scanner) (Items, error) {
	var row Items
	err := s.Scan(
		&row.ID,
		&row.Name,
	)
	return row, err
}

// IterContext returns iter.Seq2[Items, error] and closer.
//
// The returned Iter.Seq2 assembles and executes a query in the first iteration.
// Therefore, the first iteration may return an error in assembling or executing the query.
// Subsequent iterations read rows. Again, the read may return an error.
//
// closer is a function that closes the row reader object. Execution of this function is idempotent.
// Be sure to call it when you are done using iter.Seq2.
func (q itemsSelectSQL) IterContext(ctx context.Context, db sqlla.DB) (func(func(Items, error) bool), func() error) {
	var rowClose func() error
	closer := func() error {
		if rowClose != nil {
			err := rowClose()
			rowClose = nil
			return err
		}
		return nil
	}

	q.Columns = itemsAllColumns
	query, args, err := q.ToSql()
	return func(yield func(Items, error) bool) {
		if err != nil {
			var r Items
			yield(r, err)
			return
		}
		rows, err := db.QueryContext(ctx, query, args...)
		if err != nil {
			var r Items
			yield(r, err)
			return
		}
		rowClose = rows.Close
		for rows.Next() {
			r, err := q.Scan(rows)
			if !yield(r, err) {
				break
			}
		}
	}, closer
}

type itemsUpdateSQL struct {
	itemsSQL
	setMap  sqlla.SetMap
	Columns []string
}

func (q itemsSQL) Update() itemsUpdateSQL {
	return itemsUpdateSQL{
		itemsSQL: q,
		setMap:   sqlla.SetMap{},
	}
}

func (q itemsUpdateSQL) SetID(v ItemID) itemsUpdateSQL {
	q.setMap["`id`"] = v
	return q
}

func (q itemsUpdateSQL) WhereID(v ItemID, exprs ...sqlla.Operator) itemsUpdateSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q itemsUpdateSQL) WhereIDIn(vs ...ItemID) itemsUpdateSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q itemsUpdateSQL) SetName(v string) itemsUpdateSQL {
	q.setMap["`name`"] = v
	return q
}

func (q itemsUpdateSQL) WhereName(v string, exprs ...sqlla.Operator) itemsUpdateSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprString{Value: v, Op: op, Column: "`name`"}
	q.where = append(q.where, where)
	return q
}

func (q itemsUpdateSQL) WhereNameIn(vs ...string) itemsUpdateSQL {
	where := sqlla.ExprMultiString{Values: vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`name`"}
	q.where = append(q.where, where)
	return q
}

func (q itemsUpdateSQL) ToSql() (string, []interface{}, error) {
	var err error
	var s interface{} = Items{}
	if t, ok := s.(itemsDefaultUpdateHooker); ok {
		q, err = t.DefaultUpdateHook(q)
		if err != nil {
			return "", []interface{}{}, err
		}
	}
	setColumns, svs, err := q.setMap.ToUpdateSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	wheres, wvs, err := q.where.ToSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	query := "UPDATE `items` SET" + setColumns
	if wheres != "" {
		query += " WHERE" + wheres
	}

	return query + ";", append(svs, wvs...), nil
}
func (s Items) Update() itemsUpdateSQL {
	return NewItemsSQL().Update().WhereID(s.ID)
}

func (q itemsUpdateSQL) Exec(db sqlla.DB) ([]Items, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	_, err = db.Exec(query, args...)
	if err != nil {
		return nil, err
	}
	qq := q.itemsSQL

	return qq.Select().All(db)
}

func (q itemsUpdateSQL) ExecContext(ctx context.Context, db sqlla.DB) ([]Items, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	_, err = db.ExecContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	qq := q.itemsSQL

	return qq.Select().AllContext(ctx, db)
}

type itemsDefaultUpdateHooker interface {
	DefaultUpdateHook(itemsUpdateSQL) (itemsUpdateSQL, error)
}

type itemsInsertSQL struct {
	itemsSQL
	setMap  sqlla.SetMap
	Columns []string
}

func (q itemsSQL) Insert() itemsInsertSQL {
	return itemsInsertSQL{
		itemsSQL: q,
		setMap:   sqlla.SetMap{},
	}
}

func (q itemsInsertSQL) ValueID(v ItemID) itemsInsertSQL {
	q.setMap["`id`"] = v
	return q
}

func (q itemsInsertSQL) ValueName(v string) itemsInsertSQL {
	q.setMap["`name`"] = v
	return q
}

func (q itemsInsertSQL) ToSql() (string, []interface{}, error) {
	query, vs, err := q.itemsInsertSQLToSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	return query + ";", vs, nil
}

func (q itemsInsertSQL) itemsInsertSQLToSql() (string, []interface{}, error) {
	var err error
	var s interface{} = Items{}
	if t, ok := s.(itemsDefaultInsertHooker); ok {
		q, err = t.DefaultInsertHook(q)
		if err != nil {
			return "", []interface{}{}, err
		}
	}
	qs, vs, err := q.setMap.ToInsertSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	query := "INSERT INTO `items` " + qs

	return query, vs, nil
}

func (q itemsInsertSQL) OnDuplicateKeyUpdate() itemsInsertOnDuplicateKeyUpdateSQL {
	return itemsInsertOnDuplicateKeyUpdateSQL{
		insertSQL:               q,
		onDuplicateKeyUpdateMap: sqlla.SetMap{},
	}
}

func (q itemsInsertSQL) Exec(db sqlla.DB) (Items, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return Items{}, err
	}
	result, err := db.Exec(query, args...)
	if err != nil {
		return Items{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return Items{}, err
	}
	return NewItemsSQL().Select().PkColumn(id).Single(db)
}

func (q itemsInsertSQL) ExecContext(ctx context.Context, db sqlla.DB) (Items, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return Items{}, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return Items{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return Items{}, err
	}
	return NewItemsSQL().Select().PkColumn(id).SingleContext(ctx, db)
}

func (q itemsInsertSQL) ExecContextWithoutSelect(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	return result, err
}

type itemsDefaultInsertHooker interface {
	DefaultInsertHook(itemsInsertSQL) (itemsInsertSQL, error)
}

type itemsInsertSQLToSqler interface {
	itemsInsertSQLToSql() (string, []interface{}, error)
}

type itemsInsertOnDuplicateKeyUpdateSQL struct {
	insertSQL               itemsInsertSQLToSqler
	onDuplicateKeyUpdateMap sqlla.SetMap
}

func (q itemsInsertOnDuplicateKeyUpdateSQL) ValueOnUpdateID(v ItemID) itemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`id`"] = v
	return q
}

func (q itemsInsertOnDuplicateKeyUpdateSQL) RawValueOnUpdateID(v sqlla.SetMapRawValue) itemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`id`"] = v
	return q
}

func (q itemsInsertOnDuplicateKeyUpdateSQL) SameOnUpdateID() itemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`id`"] = sqlla.SetMapRawValue("VALUES(`id`)")
	return q
}

func (q itemsInsertOnDuplicateKeyUpdateSQL) ValueOnUpdateName(v string) itemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`name`"] = v
	return q
}

func (q itemsInsertOnDuplicateKeyUpdateSQL) RawValueOnUpdateName(v sqlla.SetMapRawValue) itemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`name`"] = v
	return q
}

func (q itemsInsertOnDuplicateKeyUpdateSQL) SameOnUpdateName() itemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`name`"] = sqlla.SetMapRawValue("VALUES(`name`)")
	return q
}

func (q itemsInsertOnDuplicateKeyUpdateSQL) ToSql() (string, []interface{}, error) {
	var err error
	var s interface{} = Items{}
	if t, ok := s.(itemsDefaultInsertOnDuplicateKeyUpdateHooker); ok {
		q, err = t.DefaultInsertOnDuplicateKeyUpdateHook(q)
		if err != nil {
			return "", []interface{}{}, err
		}
	}

	query, vs, err := q.insertSQL.itemsInsertSQLToSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	os, ovs, err := q.onDuplicateKeyUpdateMap.ToUpdateSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	query += " ON DUPLICATE KEY UPDATE" + os
	vs = append(vs, ovs...)

	return query + ";", vs, nil
}

func (q itemsInsertOnDuplicateKeyUpdateSQL) ExecContext(ctx context.Context, db sqlla.DB) (Items, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return Items{}, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return Items{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return Items{}, err
	}
	return NewItemsSQL().Select().PkColumn(id).SingleContext(ctx, db)
}

func (q itemsInsertOnDuplicateKeyUpdateSQL) ExecContextWithoutSelect(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	return result, err
}

type itemsDefaultInsertOnDuplicateKeyUpdateHooker interface {
	DefaultInsertOnDuplicateKeyUpdateHook(itemsInsertOnDuplicateKeyUpdateSQL) (itemsInsertOnDuplicateKeyUpdateSQL, error)
}

type itemsBulkInsertSQL struct {
	insertSQLs []itemsInsertSQL
}

func (q itemsSQL) BulkInsert() *itemsBulkInsertSQL {
	return &itemsBulkInsertSQL{
		insertSQLs: []itemsInsertSQL{},
	}
}

func (q *itemsBulkInsertSQL) Append(iqs ...itemsInsertSQL) {
	q.insertSQLs = append(q.insertSQLs, iqs...)
}

func (q *itemsBulkInsertSQL) itemsInsertSQLToSql() (string, []interface{}, error) {
	if len(q.insertSQLs) == 0 {
		return "", []interface{}{}, fmt.Errorf("sqlla: This itemsBulkInsertSQL's InsertSQL was empty")
	}
	iqs := make([]itemsInsertSQL, len(q.insertSQLs))
	copy(iqs, q.insertSQLs)

	var s interface{} = Items{}
	if t, ok := s.(itemsDefaultInsertHooker); ok {
		for i, iq := range iqs {
			var err error
			iq, err = t.DefaultInsertHook(iq)
			if err != nil {
				return "", []interface{}{}, err
			}
			iqs[i] = iq
		}
	}

	sms := make(sqlla.SetMaps, 0, len(q.insertSQLs))
	for _, iq := range q.insertSQLs {
		sms = append(sms, iq.setMap)
	}

	query, vs, err := sms.ToInsertSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	return "INSERT INTO `items` " + query, vs, nil
}

func (q *itemsBulkInsertSQL) ToSql() (string, []interface{}, error) {
	query, vs, err := q.itemsInsertSQLToSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	return query + ";", vs, nil
}

func (q *itemsBulkInsertSQL) OnDuplicateKeyUpdate() itemsInsertOnDuplicateKeyUpdateSQL {
	return itemsInsertOnDuplicateKeyUpdateSQL{
		insertSQL:               q,
		onDuplicateKeyUpdateMap: sqlla.SetMap{},
	}
}

func (q *itemsBulkInsertSQL) ExecContext(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	return result, err
}

type itemsDeleteSQL struct {
	itemsSQL
}

func (q itemsSQL) Delete() itemsDeleteSQL {
	return itemsDeleteSQL{
		q,
	}
}

func (q itemsDeleteSQL) ID(v ItemID, exprs ...sqlla.Operator) itemsDeleteSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q itemsDeleteSQL) IDIn(vs ...ItemID) itemsDeleteSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q itemsDeleteSQL) Name(v string, exprs ...sqlla.Operator) itemsDeleteSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprString{Value: v, Op: op, Column: "`name`"}
	q.where = append(q.where, where)
	return q
}

func (q itemsDeleteSQL) NameIn(vs ...string) itemsDeleteSQL {
	where := sqlla.ExprMultiString{Values: vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`name`"}
	q.where = append(q.where, where)
	return q
}

func (q itemsDeleteSQL) ToSql() (string, []interface{}, error) {
	wheres, vs, err := q.where.ToSql()
	if err != nil {
		return "", nil, err
	}

	query := "DELETE FROM `items`"
	if wheres != "" {
		query += " WHERE" + wheres
	}

	return query + ";", vs, nil
}

func (q itemsDeleteSQL) Exec(db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	return db.Exec(query, args...)
}

func (q itemsDeleteSQL) ExecContext(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	return db.ExecContext(ctx, query, args...)
}
func (s Items) Delete(db sqlla.DB) (sql.Result, error) {
	query, args, err := NewItemsSQL().Delete().ID(s.ID).ToSql()
	if err != nil {
		return nil, err
	}
	return db.Exec(query, args...)
}

func (s Items) DeleteContext(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := NewItemsSQL().Delete().ID(s.ID).ToSql()
	if err != nil {
		return nil, err
	}
	return db.ExecContext(ctx, query, args...)
}
