// Code generated by github.com/mackee/go-sqlla/v2/cmd/sqlla - DO NOT EDIT.
package asyncdataloader

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"database/sql"

	"github.com/mackee/go-sqlla/v2"
)

type userItemsSQL struct {
	where sqlla.Where
}

func NewUserItemsSQL() userItemsSQL {
	q := userItemsSQL{}
	return q
}

var userItemsAllColumns = []string{
	"`id`", "`user_id`", "`item_id`",
}

type userItemsSelectSQL struct {
	userItemsSQL
	Columns     []string
	order       string
	limit       *uint64
	offset      *uint64
	tableAlias  string
	joinClauses []string

	additionalWhereClause     string
	additionalWhereClauseArgs []interface{}

	groupByColumns []string

	isForUpdate bool
}

func (q userItemsSQL) Select() userItemsSelectSQL {
	return userItemsSelectSQL{
		q,
		userItemsAllColumns,
		"",
		nil,
		nil,
		"",
		nil,
		"",
		nil,
		nil,
		false,
	}
}

func (q userItemsSelectSQL) Or(qs ...userItemsSelectSQL) userItemsSelectSQL {
	ws := make([]sqlla.Where, 0, len(qs))
	for _, q := range qs {
		ws = append(ws, q.where)
	}
	q.where = append(q.where, sqlla.ExprOr(ws))
	return q
}

func (q userItemsSelectSQL) Limit(l uint64) userItemsSelectSQL {
	q.limit = &l
	return q
}

func (q userItemsSelectSQL) Offset(o uint64) userItemsSelectSQL {
	q.offset = &o
	return q
}

func (q userItemsSelectSQL) ForUpdate() userItemsSelectSQL {
	q.isForUpdate = true
	return q
}

func (q userItemsSelectSQL) TableAlias(alias string) userItemsSelectSQL {
	q.tableAlias = "`" + alias + "`"
	return q
}

func (q userItemsSelectSQL) SetColumns(columns ...string) userItemsSelectSQL {
	q.Columns = make([]string, 0, len(columns))
	for _, column := range columns {
		if strings.ContainsAny(column, "(.`") {
			q.Columns = append(q.Columns, column)
		} else {
			q.Columns = append(q.Columns, "`"+column+"`")
		}
	}
	return q
}

func (q userItemsSelectSQL) JoinClause(clause string) userItemsSelectSQL {
	q.joinClauses = append(q.joinClauses, clause)
	return q
}

func (q userItemsSelectSQL) AdditionalWhereClause(clause string, args ...interface{}) userItemsSelectSQL {
	q.additionalWhereClause = clause
	q.additionalWhereClauseArgs = args
	return q
}

func (q userItemsSelectSQL) appendColumnPrefix(column string) string {
	if q.tableAlias == "" || strings.ContainsAny(column, "(.") {
		return column
	}
	return q.tableAlias + "." + column
}

func (q userItemsSelectSQL) GroupBy(columns ...string) userItemsSelectSQL {
	q.groupByColumns = make([]string, 0, len(columns))
	for _, column := range columns {
		if strings.ContainsAny(column, "(.`") {
			q.groupByColumns = append(q.groupByColumns, column)
		} else {
			q.groupByColumns = append(q.groupByColumns, "`"+column+"`")
		}
	}
	return q
}

func (q userItemsSelectSQL) ID(v UserItemID, exprs ...sqlla.Operator) userItemsSelectSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: q.appendColumnPrefix("`id`")}
	q.where = append(q.where, where)
	return q
}

func (q userItemsSelectSQL) IDIn(vs ...UserItemID) userItemsSelectSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: q.appendColumnPrefix("`id`")}
	q.where = append(q.where, where)
	return q
}

func (q userItemsSelectSQL) PkColumn(pk int64, exprs ...sqlla.Operator) userItemsSelectSQL {
	v := UserItemID(pk)
	return q.ID(v, exprs...)
}

func (q userItemsSelectSQL) OrderByID(order sqlla.Order) userItemsSelectSQL {
	q.order = " ORDER BY " + q.appendColumnPrefix("`id`")
	if order == sqlla.Asc {
		q.order += " ASC"
	} else {
		q.order += " DESC"
	}

	return q
}

func (q userItemsSelectSQL) UserID(v UserID, exprs ...sqlla.Operator) userItemsSelectSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: q.appendColumnPrefix("`user_id`")}
	q.where = append(q.where, where)
	return q
}

func (q userItemsSelectSQL) UserIDIn(vs ...UserID) userItemsSelectSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: q.appendColumnPrefix("`user_id`")}
	q.where = append(q.where, where)
	return q
}

func (q userItemsSelectSQL) OrderByUserID(order sqlla.Order) userItemsSelectSQL {
	q.order = " ORDER BY " + q.appendColumnPrefix("`user_id`")
	if order == sqlla.Asc {
		q.order += " ASC"
	} else {
		q.order += " DESC"
	}

	return q
}

func (q userItemsSelectSQL) ItemID(v ItemID, exprs ...sqlla.Operator) userItemsSelectSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: q.appendColumnPrefix("`item_id`")}
	q.where = append(q.where, where)
	return q
}

func (q userItemsSelectSQL) ItemIDIn(vs ...ItemID) userItemsSelectSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: q.appendColumnPrefix("`item_id`")}
	q.where = append(q.where, where)
	return q
}

func (q userItemsSelectSQL) OrderByItemID(order sqlla.Order) userItemsSelectSQL {
	q.order = " ORDER BY " + q.appendColumnPrefix("`item_id`")
	if order == sqlla.Asc {
		q.order += " ASC"
	} else {
		q.order += " DESC"
	}

	return q
}

func (q userItemsSelectSQL) ToSql() (string, []interface{}, error) {
	columns := strings.Join(q.Columns, ", ")
	wheres, vs, err := q.where.ToSql()
	if err != nil {
		return "", nil, err
	}

	tableName := "`user_items`"
	if q.tableAlias != "" {
		tableName = tableName + " AS " + q.tableAlias
		pcs := make([]string, 0, len(q.Columns))
		for _, column := range q.Columns {
			pcs = append(pcs, q.appendColumnPrefix(column))
		}
		columns = strings.Join(pcs, ", ")
	}
	query := "SELECT " + columns + " FROM " + tableName
	if len(q.joinClauses) > 0 {
		jc := strings.Join(q.joinClauses, " ")
		query += " " + jc
	}
	if wheres != "" {
		query += " WHERE" + wheres
	}
	if q.additionalWhereClause != "" {
		query += " " + q.additionalWhereClause
		if len(q.additionalWhereClauseArgs) > 0 {
			vs = append(vs, q.additionalWhereClauseArgs...)
		}
	}
	if len(q.groupByColumns) > 0 {
		query += " GROUP BY "
		gbcs := make([]string, 0, len(q.groupByColumns))
		for _, column := range q.groupByColumns {
			gbcs = append(gbcs, q.appendColumnPrefix(column))
		}
		query += strings.Join(gbcs, ", ")
	}
	query += q.order
	if q.limit != nil {
		query += " LIMIT " + strconv.FormatUint(*q.limit, 10)
	}
	if q.offset != nil {
		query += " OFFSET " + strconv.FormatUint(*q.offset, 10)
	}

	if q.isForUpdate {
		query += " FOR UPDATE"
	}

	return query + ";", vs, nil
}

func (s UserItems) Select() userItemsSelectSQL {
	return NewUserItemsSQL().Select().ID(s.ID)
}
func (q userItemsSelectSQL) Single(db sqlla.DB) (UserItems, error) {
	q.Columns = userItemsAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return UserItems{}, err
	}

	row := db.QueryRow(query, args...)
	return q.Scan(row)
}

func (q userItemsSelectSQL) SingleContext(ctx context.Context, db sqlla.DB) (UserItems, error) {
	q.Columns = userItemsAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return UserItems{}, err
	}

	row := db.QueryRowContext(ctx, query, args...)
	return q.Scan(row)
}

func (q userItemsSelectSQL) All(db sqlla.DB) ([]UserItems, error) {
	rs := make([]UserItems, 0, 10)
	q.Columns = userItemsAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}

	rows, err := db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		r, err := q.Scan(rows)
		if err != nil {
			return nil, err
		}
		rs = append(rs, r)
	}
	return rs, nil
}

func (q userItemsSelectSQL) AllContext(ctx context.Context, db sqlla.DB) ([]UserItems, error) {
	rs := make([]UserItems, 0, 10)
	q.Columns = userItemsAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		r, err := q.Scan(rows)
		if err != nil {
			return nil, err
		}
		rs = append(rs, r)
	}
	return rs, nil
}

func (q userItemsSelectSQL) Scan(s sqlla.Scanner) (UserItems, error) {
	var row UserItems
	err := s.Scan(
		&row.ID,
		&row.UserID,
		&row.ItemID,
	)
	return row, err
}

// IterContext returns iter.Seq2[UserItems, error] and closer.
//
// The returned Iter.Seq2 assembles and executes a query in the first iteration.
// Therefore, the first iteration may return an error in assembling or executing the query.
// Subsequent iterations read rows. Again, the read may return an error.
//
// closer is a function that closes the row reader object. Execution of this function is idempotent.
// Be sure to call it when you are done using iter.Seq2.
func (q userItemsSelectSQL) IterContext(ctx context.Context, db sqlla.DB) (func(func(UserItems, error) bool), func() error) {
	var rowClose func() error
	closer := func() error {
		if rowClose != nil {
			err := rowClose()
			rowClose = nil
			return err
		}
		return nil
	}

	q.Columns = userItemsAllColumns
	query, args, err := q.ToSql()
	return func(yield func(UserItems, error) bool) {
		if err != nil {
			var r UserItems
			yield(r, err)
			return
		}
		rows, err := db.QueryContext(ctx, query, args...)
		if err != nil {
			var r UserItems
			yield(r, err)
			return
		}
		rowClose = rows.Close
		for rows.Next() {
			r, err := q.Scan(rows)
			if !yield(r, err) {
				break
			}
		}
	}, closer
}

type userItemsUpdateSQL struct {
	userItemsSQL
	setMap  sqlla.SetMap
	Columns []string
}

func (q userItemsSQL) Update() userItemsUpdateSQL {
	return userItemsUpdateSQL{
		userItemsSQL: q,
		setMap:       sqlla.SetMap{},
	}
}

func (q userItemsUpdateSQL) SetID(v UserItemID) userItemsUpdateSQL {
	q.setMap["`id`"] = v
	return q
}

func (q userItemsUpdateSQL) WhereID(v UserItemID, exprs ...sqlla.Operator) userItemsUpdateSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsUpdateSQL) WhereIDIn(vs ...UserItemID) userItemsUpdateSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsUpdateSQL) SetUserID(v UserID) userItemsUpdateSQL {
	q.setMap["`user_id`"] = v
	return q
}

func (q userItemsUpdateSQL) WhereUserID(v UserID, exprs ...sqlla.Operator) userItemsUpdateSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`user_id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsUpdateSQL) WhereUserIDIn(vs ...UserID) userItemsUpdateSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`user_id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsUpdateSQL) SetItemID(v ItemID) userItemsUpdateSQL {
	q.setMap["`item_id`"] = v
	return q
}

func (q userItemsUpdateSQL) WhereItemID(v ItemID, exprs ...sqlla.Operator) userItemsUpdateSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`item_id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsUpdateSQL) WhereItemIDIn(vs ...ItemID) userItemsUpdateSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`item_id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsUpdateSQL) ToSql() (string, []interface{}, error) {
	var err error
	var s interface{} = UserItems{}
	if t, ok := s.(userItemsDefaultUpdateHooker); ok {
		q, err = t.DefaultUpdateHook(q)
		if err != nil {
			return "", []interface{}{}, err
		}
	}
	setColumns, svs, err := q.setMap.ToUpdateSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	wheres, wvs, err := q.where.ToSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	query := "UPDATE `user_items` SET" + setColumns
	if wheres != "" {
		query += " WHERE" + wheres
	}

	return query + ";", append(svs, wvs...), nil
}
func (s UserItems) Update() userItemsUpdateSQL {
	return NewUserItemsSQL().Update().WhereID(s.ID)
}

func (q userItemsUpdateSQL) Exec(db sqlla.DB) ([]UserItems, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	_, err = db.Exec(query, args...)
	if err != nil {
		return nil, err
	}
	qq := q.userItemsSQL

	return qq.Select().All(db)
}

func (q userItemsUpdateSQL) ExecContext(ctx context.Context, db sqlla.DB) ([]UserItems, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	_, err = db.ExecContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	qq := q.userItemsSQL

	return qq.Select().AllContext(ctx, db)
}

type userItemsDefaultUpdateHooker interface {
	DefaultUpdateHook(userItemsUpdateSQL) (userItemsUpdateSQL, error)
}

type userItemsInsertSQL struct {
	userItemsSQL
	setMap  sqlla.SetMap
	Columns []string
}

func (q userItemsSQL) Insert() userItemsInsertSQL {
	return userItemsInsertSQL{
		userItemsSQL: q,
		setMap:       sqlla.SetMap{},
	}
}

func (q userItemsInsertSQL) ValueID(v UserItemID) userItemsInsertSQL {
	q.setMap["`id`"] = v
	return q
}

func (q userItemsInsertSQL) ValueUserID(v UserID) userItemsInsertSQL {
	q.setMap["`user_id`"] = v
	return q
}

func (q userItemsInsertSQL) ValueItemID(v ItemID) userItemsInsertSQL {
	q.setMap["`item_id`"] = v
	return q
}

func (q userItemsInsertSQL) ToSql() (string, []interface{}, error) {
	query, vs, err := q.userItemsInsertSQLToSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	return query + ";", vs, nil
}

func (q userItemsInsertSQL) userItemsInsertSQLToSql() (string, []interface{}, error) {
	var err error
	var s interface{} = UserItems{}
	if t, ok := s.(userItemsDefaultInsertHooker); ok {
		q, err = t.DefaultInsertHook(q)
		if err != nil {
			return "", []interface{}{}, err
		}
	}
	qs, vs, err := q.setMap.ToInsertSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	query := "INSERT INTO `user_items` " + qs

	return query, vs, nil
}

func (q userItemsInsertSQL) OnDuplicateKeyUpdate() userItemsInsertOnDuplicateKeyUpdateSQL {
	return userItemsInsertOnDuplicateKeyUpdateSQL{
		insertSQL:               q,
		onDuplicateKeyUpdateMap: sqlla.SetMap{},
	}
}

func (q userItemsInsertSQL) Exec(db sqlla.DB) (UserItems, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return UserItems{}, err
	}
	result, err := db.Exec(query, args...)
	if err != nil {
		return UserItems{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return UserItems{}, err
	}
	return NewUserItemsSQL().Select().PkColumn(id).Single(db)
}

func (q userItemsInsertSQL) ExecContext(ctx context.Context, db sqlla.DB) (UserItems, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return UserItems{}, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return UserItems{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return UserItems{}, err
	}
	return NewUserItemsSQL().Select().PkColumn(id).SingleContext(ctx, db)
}

func (q userItemsInsertSQL) ExecContextWithoutSelect(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	return result, err
}

type userItemsDefaultInsertHooker interface {
	DefaultInsertHook(userItemsInsertSQL) (userItemsInsertSQL, error)
}

type userItemsInsertSQLToSqler interface {
	userItemsInsertSQLToSql() (string, []interface{}, error)
}

type userItemsInsertOnDuplicateKeyUpdateSQL struct {
	insertSQL               userItemsInsertSQLToSqler
	onDuplicateKeyUpdateMap sqlla.SetMap
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) ValueOnUpdateID(v UserItemID) userItemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`id`"] = v
	return q
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) RawValueOnUpdateID(v sqlla.SetMapRawValue) userItemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`id`"] = v
	return q
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) SameOnUpdateID() userItemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`id`"] = sqlla.SetMapRawValue("VALUES(`id`)")
	return q
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) ValueOnUpdateUserID(v UserID) userItemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`user_id`"] = v
	return q
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) RawValueOnUpdateUserID(v sqlla.SetMapRawValue) userItemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`user_id`"] = v
	return q
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) SameOnUpdateUserID() userItemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`user_id`"] = sqlla.SetMapRawValue("VALUES(`user_id`)")
	return q
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) ValueOnUpdateItemID(v ItemID) userItemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`item_id`"] = v
	return q
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) RawValueOnUpdateItemID(v sqlla.SetMapRawValue) userItemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`item_id`"] = v
	return q
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) SameOnUpdateItemID() userItemsInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`item_id`"] = sqlla.SetMapRawValue("VALUES(`item_id`)")
	return q
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) ToSql() (string, []interface{}, error) {
	var err error
	var s interface{} = UserItems{}
	if t, ok := s.(userItemsDefaultInsertOnDuplicateKeyUpdateHooker); ok {
		q, err = t.DefaultInsertOnDuplicateKeyUpdateHook(q)
		if err != nil {
			return "", []interface{}{}, err
		}
	}

	query, vs, err := q.insertSQL.userItemsInsertSQLToSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	os, ovs, err := q.onDuplicateKeyUpdateMap.ToUpdateSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	query += " ON DUPLICATE KEY UPDATE" + os
	vs = append(vs, ovs...)

	return query + ";", vs, nil
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) ExecContext(ctx context.Context, db sqlla.DB) (UserItems, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return UserItems{}, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return UserItems{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return UserItems{}, err
	}
	return NewUserItemsSQL().Select().PkColumn(id).SingleContext(ctx, db)
}

func (q userItemsInsertOnDuplicateKeyUpdateSQL) ExecContextWithoutSelect(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	return result, err
}

type userItemsDefaultInsertOnDuplicateKeyUpdateHooker interface {
	DefaultInsertOnDuplicateKeyUpdateHook(userItemsInsertOnDuplicateKeyUpdateSQL) (userItemsInsertOnDuplicateKeyUpdateSQL, error)
}

type userItemsBulkInsertSQL struct {
	insertSQLs []userItemsInsertSQL
}

func (q userItemsSQL) BulkInsert() *userItemsBulkInsertSQL {
	return &userItemsBulkInsertSQL{
		insertSQLs: []userItemsInsertSQL{},
	}
}

func (q *userItemsBulkInsertSQL) Append(iqs ...userItemsInsertSQL) {
	q.insertSQLs = append(q.insertSQLs, iqs...)
}

func (q *userItemsBulkInsertSQL) userItemsInsertSQLToSql() (string, []interface{}, error) {
	if len(q.insertSQLs) == 0 {
		return "", []interface{}{}, fmt.Errorf("sqlla: This userItemsBulkInsertSQL's InsertSQL was empty")
	}
	iqs := make([]userItemsInsertSQL, len(q.insertSQLs))
	copy(iqs, q.insertSQLs)

	var s interface{} = UserItems{}
	if t, ok := s.(userItemsDefaultInsertHooker); ok {
		for i, iq := range iqs {
			var err error
			iq, err = t.DefaultInsertHook(iq)
			if err != nil {
				return "", []interface{}{}, err
			}
			iqs[i] = iq
		}
	}

	sms := make(sqlla.SetMaps, 0, len(q.insertSQLs))
	for _, iq := range q.insertSQLs {
		sms = append(sms, iq.setMap)
	}

	query, vs, err := sms.ToInsertSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	return "INSERT INTO `user_items` " + query, vs, nil
}

func (q *userItemsBulkInsertSQL) ToSql() (string, []interface{}, error) {
	query, vs, err := q.userItemsInsertSQLToSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	return query + ";", vs, nil
}

func (q *userItemsBulkInsertSQL) OnDuplicateKeyUpdate() userItemsInsertOnDuplicateKeyUpdateSQL {
	return userItemsInsertOnDuplicateKeyUpdateSQL{
		insertSQL:               q,
		onDuplicateKeyUpdateMap: sqlla.SetMap{},
	}
}

func (q *userItemsBulkInsertSQL) ExecContext(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	return result, err
}

type userItemsDeleteSQL struct {
	userItemsSQL
}

func (q userItemsSQL) Delete() userItemsDeleteSQL {
	return userItemsDeleteSQL{
		q,
	}
}

func (q userItemsDeleteSQL) ID(v UserItemID, exprs ...sqlla.Operator) userItemsDeleteSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsDeleteSQL) IDIn(vs ...UserItemID) userItemsDeleteSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsDeleteSQL) UserID(v UserID, exprs ...sqlla.Operator) userItemsDeleteSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`user_id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsDeleteSQL) UserIDIn(vs ...UserID) userItemsDeleteSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`user_id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsDeleteSQL) ItemID(v ItemID, exprs ...sqlla.Operator) userItemsDeleteSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`item_id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsDeleteSQL) ItemIDIn(vs ...ItemID) userItemsDeleteSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`item_id`"}
	q.where = append(q.where, where)
	return q
}

func (q userItemsDeleteSQL) ToSql() (string, []interface{}, error) {
	wheres, vs, err := q.where.ToSql()
	if err != nil {
		return "", nil, err
	}

	query := "DELETE FROM `user_items`"
	if wheres != "" {
		query += " WHERE" + wheres
	}

	return query + ";", vs, nil
}

func (q userItemsDeleteSQL) Exec(db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	return db.Exec(query, args...)
}

func (q userItemsDeleteSQL) ExecContext(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	return db.ExecContext(ctx, query, args...)
}
func (s UserItems) Delete(db sqlla.DB) (sql.Result, error) {
	query, args, err := NewUserItemsSQL().Delete().ID(s.ID).ToSql()
	if err != nil {
		return nil, err
	}
	return db.Exec(query, args...)
}

func (s UserItems) DeleteContext(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := NewUserItemsSQL().Delete().ID(s.ID).ToSql()
	if err != nil {
		return nil, err
	}
	return db.ExecContext(ctx, query, args...)
}
