// Code generated by github.com/mackee/go-sqlla/v2/cmd/sqlla - DO NOT EDIT.
package asyncdataloader

import (
	"context"
	"fmt"
	"strconv"
	"strings"

	"database/sql"

	"github.com/mackee/go-sqlla/v2"
)

type usersSQL struct {
	where sqlla.Where
}

func NewUsersSQL() usersSQL {
	q := usersSQL{}
	return q
}

var usersAllColumns = []string{
	"`id`", "`name`",
}

type usersSelectSQL struct {
	usersSQL
	Columns     []string
	order       string
	limit       *uint64
	offset      *uint64
	tableAlias  string
	joinClauses []string

	additionalWhereClause     string
	additionalWhereClauseArgs []interface{}

	groupByColumns []string

	isForUpdate bool
}

func (q usersSQL) Select() usersSelectSQL {
	return usersSelectSQL{
		q,
		usersAllColumns,
		"",
		nil,
		nil,
		"",
		nil,
		"",
		nil,
		nil,
		false,
	}
}

func (q usersSelectSQL) Or(qs ...usersSelectSQL) usersSelectSQL {
	ws := make([]sqlla.Where, 0, len(qs))
	for _, q := range qs {
		ws = append(ws, q.where)
	}
	q.where = append(q.where, sqlla.ExprOr(ws))
	return q
}

func (q usersSelectSQL) Limit(l uint64) usersSelectSQL {
	q.limit = &l
	return q
}

func (q usersSelectSQL) Offset(o uint64) usersSelectSQL {
	q.offset = &o
	return q
}

func (q usersSelectSQL) ForUpdate() usersSelectSQL {
	q.isForUpdate = true
	return q
}

func (q usersSelectSQL) TableAlias(alias string) usersSelectSQL {
	q.tableAlias = "`" + alias + "`"
	return q
}

func (q usersSelectSQL) SetColumns(columns ...string) usersSelectSQL {
	q.Columns = make([]string, 0, len(columns))
	for _, column := range columns {
		if strings.ContainsAny(column, "(.`") {
			q.Columns = append(q.Columns, column)
		} else {
			q.Columns = append(q.Columns, "`"+column+"`")
		}
	}
	return q
}

func (q usersSelectSQL) JoinClause(clause string) usersSelectSQL {
	q.joinClauses = append(q.joinClauses, clause)
	return q
}

func (q usersSelectSQL) AdditionalWhereClause(clause string, args ...interface{}) usersSelectSQL {
	q.additionalWhereClause = clause
	q.additionalWhereClauseArgs = args
	return q
}

func (q usersSelectSQL) appendColumnPrefix(column string) string {
	if q.tableAlias == "" || strings.ContainsAny(column, "(.") {
		return column
	}
	return q.tableAlias + "." + column
}

func (q usersSelectSQL) GroupBy(columns ...string) usersSelectSQL {
	q.groupByColumns = make([]string, 0, len(columns))
	for _, column := range columns {
		if strings.ContainsAny(column, "(.`") {
			q.groupByColumns = append(q.groupByColumns, column)
		} else {
			q.groupByColumns = append(q.groupByColumns, "`"+column+"`")
		}
	}
	return q
}

func (q usersSelectSQL) ID(v UserID, exprs ...sqlla.Operator) usersSelectSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: q.appendColumnPrefix("`id`")}
	q.where = append(q.where, where)
	return q
}

func (q usersSelectSQL) IDIn(vs ...UserID) usersSelectSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: q.appendColumnPrefix("`id`")}
	q.where = append(q.where, where)
	return q
}

func (q usersSelectSQL) PkColumn(pk int64, exprs ...sqlla.Operator) usersSelectSQL {
	v := UserID(pk)
	return q.ID(v, exprs...)
}

func (q usersSelectSQL) OrderByID(order sqlla.Order) usersSelectSQL {
	q.order = " ORDER BY " + q.appendColumnPrefix("`id`")
	if order == sqlla.Asc {
		q.order += " ASC"
	} else {
		q.order += " DESC"
	}

	return q
}

func (q usersSelectSQL) Name(v string, exprs ...sqlla.Operator) usersSelectSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprString{Value: v, Op: op, Column: q.appendColumnPrefix("`name`")}
	q.where = append(q.where, where)
	return q
}

func (q usersSelectSQL) NameIn(vs ...string) usersSelectSQL {
	where := sqlla.ExprMultiString{Values: vs, Op: sqlla.MakeInOperator(len(vs)), Column: q.appendColumnPrefix("`name`")}
	q.where = append(q.where, where)
	return q
}

func (q usersSelectSQL) OrderByName(order sqlla.Order) usersSelectSQL {
	q.order = " ORDER BY " + q.appendColumnPrefix("`name`")
	if order == sqlla.Asc {
		q.order += " ASC"
	} else {
		q.order += " DESC"
	}

	return q
}

func (q usersSelectSQL) ToSql() (string, []interface{}, error) {
	columns := strings.Join(q.Columns, ", ")
	wheres, vs, err := q.where.ToSql()
	if err != nil {
		return "", nil, err
	}

	tableName := "`users`"
	if q.tableAlias != "" {
		tableName = tableName + " AS " + q.tableAlias
		pcs := make([]string, 0, len(q.Columns))
		for _, column := range q.Columns {
			pcs = append(pcs, q.appendColumnPrefix(column))
		}
		columns = strings.Join(pcs, ", ")
	}
	query := "SELECT " + columns + " FROM " + tableName
	if len(q.joinClauses) > 0 {
		jc := strings.Join(q.joinClauses, " ")
		query += " " + jc
	}
	if wheres != "" {
		query += " WHERE" + wheres
	}
	if q.additionalWhereClause != "" {
		query += " " + q.additionalWhereClause
		if len(q.additionalWhereClauseArgs) > 0 {
			vs = append(vs, q.additionalWhereClauseArgs...)
		}
	}
	if len(q.groupByColumns) > 0 {
		query += " GROUP BY "
		gbcs := make([]string, 0, len(q.groupByColumns))
		for _, column := range q.groupByColumns {
			gbcs = append(gbcs, q.appendColumnPrefix(column))
		}
		query += strings.Join(gbcs, ", ")
	}
	query += q.order
	if q.limit != nil {
		query += " LIMIT " + strconv.FormatUint(*q.limit, 10)
	}
	if q.offset != nil {
		query += " OFFSET " + strconv.FormatUint(*q.offset, 10)
	}

	if q.isForUpdate {
		query += " FOR UPDATE"
	}

	return query + ";", vs, nil
}

func (s Users) Select() usersSelectSQL {
	return NewUsersSQL().Select().ID(s.ID)
}
func (q usersSelectSQL) Single(db sqlla.DB) (Users, error) {
	q.Columns = usersAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return Users{}, err
	}

	row := db.QueryRow(query, args...)
	return q.Scan(row)
}

func (q usersSelectSQL) SingleContext(ctx context.Context, db sqlla.DB) (Users, error) {
	q.Columns = usersAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return Users{}, err
	}

	row := db.QueryRowContext(ctx, query, args...)
	return q.Scan(row)
}

func (q usersSelectSQL) All(db sqlla.DB) ([]Users, error) {
	rs := make([]Users, 0, 10)
	q.Columns = usersAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}

	rows, err := db.Query(query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		r, err := q.Scan(rows)
		if err != nil {
			return nil, err
		}
		rs = append(rs, r)
	}
	return rs, nil
}

func (q usersSelectSQL) AllContext(ctx context.Context, db sqlla.DB) ([]Users, error) {
	rs := make([]Users, 0, 10)
	q.Columns = usersAllColumns
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}

	rows, err := db.QueryContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	for rows.Next() {
		r, err := q.Scan(rows)
		if err != nil {
			return nil, err
		}
		rs = append(rs, r)
	}
	return rs, nil
}

func (q usersSelectSQL) Scan(s sqlla.Scanner) (Users, error) {
	var row Users
	err := s.Scan(
		&row.ID,
		&row.Name,
	)
	return row, err
}

// IterContext returns iter.Seq2[Users, error] and closer.
//
// The returned Iter.Seq2 assembles and executes a query in the first iteration.
// Therefore, the first iteration may return an error in assembling or executing the query.
// Subsequent iterations read rows. Again, the read may return an error.
//
// closer is a function that closes the row reader object. Execution of this function is idempotent.
// Be sure to call it when you are done using iter.Seq2.
func (q usersSelectSQL) IterContext(ctx context.Context, db sqlla.DB) (func(func(Users, error) bool), func() error) {
	var rowClose func() error
	closer := func() error {
		if rowClose != nil {
			err := rowClose()
			rowClose = nil
			return err
		}
		return nil
	}

	q.Columns = usersAllColumns
	query, args, err := q.ToSql()
	return func(yield func(Users, error) bool) {
		if err != nil {
			var r Users
			yield(r, err)
			return
		}
		rows, err := db.QueryContext(ctx, query, args...)
		if err != nil {
			var r Users
			yield(r, err)
			return
		}
		rowClose = rows.Close
		for rows.Next() {
			r, err := q.Scan(rows)
			if !yield(r, err) {
				break
			}
		}
	}, closer
}

type usersUpdateSQL struct {
	usersSQL
	setMap  sqlla.SetMap
	Columns []string
}

func (q usersSQL) Update() usersUpdateSQL {
	return usersUpdateSQL{
		usersSQL: q,
		setMap:   sqlla.SetMap{},
	}
}

func (q usersUpdateSQL) SetID(v UserID) usersUpdateSQL {
	q.setMap["`id`"] = v
	return q
}

func (q usersUpdateSQL) WhereID(v UserID, exprs ...sqlla.Operator) usersUpdateSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q usersUpdateSQL) WhereIDIn(vs ...UserID) usersUpdateSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q usersUpdateSQL) SetName(v string) usersUpdateSQL {
	q.setMap["`name`"] = v
	return q
}

func (q usersUpdateSQL) WhereName(v string, exprs ...sqlla.Operator) usersUpdateSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprString{Value: v, Op: op, Column: "`name`"}
	q.where = append(q.where, where)
	return q
}

func (q usersUpdateSQL) WhereNameIn(vs ...string) usersUpdateSQL {
	where := sqlla.ExprMultiString{Values: vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`name`"}
	q.where = append(q.where, where)
	return q
}

func (q usersUpdateSQL) ToSql() (string, []interface{}, error) {
	var err error
	var s interface{} = Users{}
	if t, ok := s.(usersDefaultUpdateHooker); ok {
		q, err = t.DefaultUpdateHook(q)
		if err != nil {
			return "", []interface{}{}, err
		}
	}
	setColumns, svs, err := q.setMap.ToUpdateSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	wheres, wvs, err := q.where.ToSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	query := "UPDATE `users` SET" + setColumns
	if wheres != "" {
		query += " WHERE" + wheres
	}

	return query + ";", append(svs, wvs...), nil
}
func (s Users) Update() usersUpdateSQL {
	return NewUsersSQL().Update().WhereID(s.ID)
}

func (q usersUpdateSQL) Exec(db sqlla.DB) ([]Users, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	_, err = db.Exec(query, args...)
	if err != nil {
		return nil, err
	}
	qq := q.usersSQL

	return qq.Select().All(db)
}

func (q usersUpdateSQL) ExecContext(ctx context.Context, db sqlla.DB) ([]Users, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	_, err = db.ExecContext(ctx, query, args...)
	if err != nil {
		return nil, err
	}
	qq := q.usersSQL

	return qq.Select().AllContext(ctx, db)
}

type usersDefaultUpdateHooker interface {
	DefaultUpdateHook(usersUpdateSQL) (usersUpdateSQL, error)
}

type usersInsertSQL struct {
	usersSQL
	setMap  sqlla.SetMap
	Columns []string
}

func (q usersSQL) Insert() usersInsertSQL {
	return usersInsertSQL{
		usersSQL: q,
		setMap:   sqlla.SetMap{},
	}
}

func (q usersInsertSQL) ValueID(v UserID) usersInsertSQL {
	q.setMap["`id`"] = v
	return q
}

func (q usersInsertSQL) ValueName(v string) usersInsertSQL {
	q.setMap["`name`"] = v
	return q
}

func (q usersInsertSQL) ToSql() (string, []interface{}, error) {
	query, vs, err := q.usersInsertSQLToSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	return query + ";", vs, nil
}

func (q usersInsertSQL) usersInsertSQLToSql() (string, []interface{}, error) {
	var err error
	var s interface{} = Users{}
	if t, ok := s.(usersDefaultInsertHooker); ok {
		q, err = t.DefaultInsertHook(q)
		if err != nil {
			return "", []interface{}{}, err
		}
	}
	qs, vs, err := q.setMap.ToInsertSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	query := "INSERT INTO `users` " + qs

	return query, vs, nil
}

func (q usersInsertSQL) OnDuplicateKeyUpdate() usersInsertOnDuplicateKeyUpdateSQL {
	return usersInsertOnDuplicateKeyUpdateSQL{
		insertSQL:               q,
		onDuplicateKeyUpdateMap: sqlla.SetMap{},
	}
}

func (q usersInsertSQL) Exec(db sqlla.DB) (Users, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return Users{}, err
	}
	result, err := db.Exec(query, args...)
	if err != nil {
		return Users{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return Users{}, err
	}
	return NewUsersSQL().Select().PkColumn(id).Single(db)
}

func (q usersInsertSQL) ExecContext(ctx context.Context, db sqlla.DB) (Users, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return Users{}, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return Users{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return Users{}, err
	}
	return NewUsersSQL().Select().PkColumn(id).SingleContext(ctx, db)
}

func (q usersInsertSQL) ExecContextWithoutSelect(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	return result, err
}

type usersDefaultInsertHooker interface {
	DefaultInsertHook(usersInsertSQL) (usersInsertSQL, error)
}

type usersInsertSQLToSqler interface {
	usersInsertSQLToSql() (string, []interface{}, error)
}

type usersInsertOnDuplicateKeyUpdateSQL struct {
	insertSQL               usersInsertSQLToSqler
	onDuplicateKeyUpdateMap sqlla.SetMap
}

func (q usersInsertOnDuplicateKeyUpdateSQL) ValueOnUpdateID(v UserID) usersInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`id`"] = v
	return q
}

func (q usersInsertOnDuplicateKeyUpdateSQL) RawValueOnUpdateID(v sqlla.SetMapRawValue) usersInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`id`"] = v
	return q
}

func (q usersInsertOnDuplicateKeyUpdateSQL) SameOnUpdateID() usersInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`id`"] = sqlla.SetMapRawValue("VALUES(`id`)")
	return q
}

func (q usersInsertOnDuplicateKeyUpdateSQL) ValueOnUpdateName(v string) usersInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`name`"] = v
	return q
}

func (q usersInsertOnDuplicateKeyUpdateSQL) RawValueOnUpdateName(v sqlla.SetMapRawValue) usersInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`name`"] = v
	return q
}

func (q usersInsertOnDuplicateKeyUpdateSQL) SameOnUpdateName() usersInsertOnDuplicateKeyUpdateSQL {
	q.onDuplicateKeyUpdateMap["`name`"] = sqlla.SetMapRawValue("VALUES(`name`)")
	return q
}

func (q usersInsertOnDuplicateKeyUpdateSQL) ToSql() (string, []interface{}, error) {
	var err error
	var s interface{} = Users{}
	if t, ok := s.(usersDefaultInsertOnDuplicateKeyUpdateHooker); ok {
		q, err = t.DefaultInsertOnDuplicateKeyUpdateHook(q)
		if err != nil {
			return "", []interface{}{}, err
		}
	}

	query, vs, err := q.insertSQL.usersInsertSQLToSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	os, ovs, err := q.onDuplicateKeyUpdateMap.ToUpdateSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	query += " ON DUPLICATE KEY UPDATE" + os
	vs = append(vs, ovs...)

	return query + ";", vs, nil
}

func (q usersInsertOnDuplicateKeyUpdateSQL) ExecContext(ctx context.Context, db sqlla.DB) (Users, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return Users{}, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	if err != nil {
		return Users{}, err
	}
	id, err := result.LastInsertId()
	if err != nil {
		return Users{}, err
	}
	return NewUsersSQL().Select().PkColumn(id).SingleContext(ctx, db)
}

func (q usersInsertOnDuplicateKeyUpdateSQL) ExecContextWithoutSelect(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	return result, err
}

type usersDefaultInsertOnDuplicateKeyUpdateHooker interface {
	DefaultInsertOnDuplicateKeyUpdateHook(usersInsertOnDuplicateKeyUpdateSQL) (usersInsertOnDuplicateKeyUpdateSQL, error)
}

type usersBulkInsertSQL struct {
	insertSQLs []usersInsertSQL
}

func (q usersSQL) BulkInsert() *usersBulkInsertSQL {
	return &usersBulkInsertSQL{
		insertSQLs: []usersInsertSQL{},
	}
}

func (q *usersBulkInsertSQL) Append(iqs ...usersInsertSQL) {
	q.insertSQLs = append(q.insertSQLs, iqs...)
}

func (q *usersBulkInsertSQL) usersInsertSQLToSql() (string, []interface{}, error) {
	if len(q.insertSQLs) == 0 {
		return "", []interface{}{}, fmt.Errorf("sqlla: This usersBulkInsertSQL's InsertSQL was empty")
	}
	iqs := make([]usersInsertSQL, len(q.insertSQLs))
	copy(iqs, q.insertSQLs)

	var s interface{} = Users{}
	if t, ok := s.(usersDefaultInsertHooker); ok {
		for i, iq := range iqs {
			var err error
			iq, err = t.DefaultInsertHook(iq)
			if err != nil {
				return "", []interface{}{}, err
			}
			iqs[i] = iq
		}
	}

	sms := make(sqlla.SetMaps, 0, len(q.insertSQLs))
	for _, iq := range q.insertSQLs {
		sms = append(sms, iq.setMap)
	}

	query, vs, err := sms.ToInsertSql()
	if err != nil {
		return "", []interface{}{}, err
	}

	return "INSERT INTO `users` " + query, vs, nil
}

func (q *usersBulkInsertSQL) ToSql() (string, []interface{}, error) {
	query, vs, err := q.usersInsertSQLToSql()
	if err != nil {
		return "", []interface{}{}, err
	}
	return query + ";", vs, nil
}

func (q *usersBulkInsertSQL) OnDuplicateKeyUpdate() usersInsertOnDuplicateKeyUpdateSQL {
	return usersInsertOnDuplicateKeyUpdateSQL{
		insertSQL:               q,
		onDuplicateKeyUpdateMap: sqlla.SetMap{},
	}
}

func (q *usersBulkInsertSQL) ExecContext(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	result, err := db.ExecContext(ctx, query, args...)
	return result, err
}

type usersDeleteSQL struct {
	usersSQL
}

func (q usersSQL) Delete() usersDeleteSQL {
	return usersDeleteSQL{
		q,
	}
}

func (q usersDeleteSQL) ID(v UserID, exprs ...sqlla.Operator) usersDeleteSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprInt64{Value: int64(v), Op: op, Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q usersDeleteSQL) IDIn(vs ...UserID) usersDeleteSQL {
	_vs := make([]int64, 0, len(vs))
	for _, v := range vs {
		_vs = append(_vs, int64(v))
	}
	where := sqlla.ExprMultiInt64{Values: _vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`id`"}
	q.where = append(q.where, where)
	return q
}

func (q usersDeleteSQL) Name(v string, exprs ...sqlla.Operator) usersDeleteSQL {
	var op sqlla.Operator
	if len(exprs) == 0 {
		op = sqlla.OpEqual
	} else {
		op = exprs[0]
	}
	where := sqlla.ExprString{Value: v, Op: op, Column: "`name`"}
	q.where = append(q.where, where)
	return q
}

func (q usersDeleteSQL) NameIn(vs ...string) usersDeleteSQL {
	where := sqlla.ExprMultiString{Values: vs, Op: sqlla.MakeInOperator(len(vs)), Column: "`name`"}
	q.where = append(q.where, where)
	return q
}

func (q usersDeleteSQL) ToSql() (string, []interface{}, error) {
	wheres, vs, err := q.where.ToSql()
	if err != nil {
		return "", nil, err
	}

	query := "DELETE FROM `users`"
	if wheres != "" {
		query += " WHERE" + wheres
	}

	return query + ";", vs, nil
}

func (q usersDeleteSQL) Exec(db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	return db.Exec(query, args...)
}

func (q usersDeleteSQL) ExecContext(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := q.ToSql()
	if err != nil {
		return nil, err
	}
	return db.ExecContext(ctx, query, args...)
}
func (s Users) Delete(db sqlla.DB) (sql.Result, error) {
	query, args, err := NewUsersSQL().Delete().ID(s.ID).ToSql()
	if err != nil {
		return nil, err
	}
	return db.Exec(query, args...)
}

func (s Users) DeleteContext(ctx context.Context, db sqlla.DB) (sql.Result, error) {
	query, args, err := NewUsersSQL().Delete().ID(s.ID).ToSql()
	if err != nil {
		return nil, err
	}
	return db.ExecContext(ctx, query, args...)
}
